// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwEnum.proto

#include "xHal_Rpi5CarXIwEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xwalk {
namespace iw {
namespace v1 {
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[8];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xHal_5fRpi5CarXIwEnum_2eproto = nullptr;
const uint32_t TableStruct_xHal_5fRpi5CarXIwEnum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xHal_5fRpi5CarXIwEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031xHal_Rpi5CarXIwEnum.proto\022\013xwalk.iw.v1"
  "*\304\001\n\021XWalkI2cOperation\022#\n\037XWALK_I2C_OPER"
  "ATION_UNSPECIFIED\020\000\022\035\n\031XWALK_I2C_OPERATI"
  "ON_PROBE\020\001\022\034\n\030XWALK_I2C_OPERATION_READ\020\002"
  "\022%\n!XWALK_I2C_OPERATION_READ_REGISTER\020\003\022"
  "&\n\"XWALK_I2C_OPERATION_WRITE_REGISTER\020\004*"
  "\230\001\n\023XWalkSoundOperation\022\036\n\032XWALK_SOUND_O"
  "PERATION_PLAY\020\000\022 \n\034XWALK_SOUND_OPERATION"
  "_VOLUME\020\001\022\037\n\033XWALK_SOUND_OPERATION_MUSIC"
  "\020\002\022\036\n\032XWALK_SOUND_OPERATION_STOP\020\003*Y\n\024XW"
  "alkLifecycleAction\022 \n\034XWALK_LIFECYCLE_AC"
  "TION_START\020\000\022\037\n\033XWALK_LIFECYCLE_ACTION_S"
  "TOP\020\001*l\n\017XWalkMoveAction\022\035\n\031XWALK_MOVE_A"
  "CTION_FORWARD\020\000\022\036\n\032XWALK_MOVE_ACTION_BAC"
  "KWARD\020\001\022\032\n\026XWALK_MOVE_ACTION_DEMO\020\002*S\n\022X"
  "WalkTurnDirection\022\035\n\031XWALK_TURN_DIRECTIO"
  "N_LEFT\020\000\022\036\n\032XWALK_TURN_DIRECTION_RIGHT\020\001"
  "*H\n\017XWalkCameraAxis\022\031\n\025XWALK_CAMERA_AXIS"
  "_PAN\020\000\022\032\n\026XWALK_CAMERA_AXIS_TILT\020\001*R\n\017XW"
  "alkSensorType\022\036\n\032XWALK_SENSOR_TYPE_DISTA"
  "NCE\020\000\022\037\n\033XWALK_SENSOR_TYPE_GRAYSCALE\020\001*\211"
  "\001\n\024XWalkCalibrationMode\022#\n\037XWALK_CALIBRA"
  "TION_MODE_COMPLETE\020\000\022$\n XWALK_CALIBRATIO"
  "N_MODE_GRAYSCALE\020\001\022&\n\"XWALK_CALIBRATION_"
  "MODE_SERVO_MOTOR\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto = {
    false, false, 986, descriptor_table_protodef_xHal_5fRpi5CarXIwEnum_2eproto,
    "xHal_Rpi5CarXIwEnum.proto",
    &descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_xHal_5fRpi5CarXIwEnum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto,
    file_level_service_descriptors_xHal_5fRpi5CarXIwEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto_getter() {
  return &descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xHal_5fRpi5CarXIwEnum_2eproto(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
namespace xwalk {
namespace iw {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkI2cOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[0];
}
bool XWalkI2cOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSoundOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[1];
}
bool XWalkSoundOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkLifecycleAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[2];
}
bool XWalkLifecycleAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkMoveAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[3];
}
bool XWalkMoveAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkTurnDirection_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[4];
}
bool XWalkTurnDirection_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkCameraAxis_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[5];
}
bool XWalkCameraAxis_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSensorType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[6];
}
bool XWalkSensorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkCalibrationMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[7];
}
bool XWalkCalibrationMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
