// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
#include "xHal_Rpi5CarXIwEnum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xHal_5fRpi5CarXIwMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_xHal_5fRpi5CarXIwMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto;
namespace xwalk {
namespace iw {
namespace v1 {
class XWalkI2cConfirmPayload;
struct XWalkI2cConfirmPayloadDefaultTypeInternal;
extern XWalkI2cConfirmPayloadDefaultTypeInternal _XWalkI2cConfirmPayload_default_instance_;
class XWalkI2cRejectPayload;
struct XWalkI2cRejectPayloadDefaultTypeInternal;
extern XWalkI2cRejectPayloadDefaultTypeInternal _XWalkI2cRejectPayload_default_instance_;
class XWalkI2cRequestPayload;
struct XWalkI2cRequestPayloadDefaultTypeInternal;
extern XWalkI2cRequestPayloadDefaultTypeInternal _XWalkI2cRequestPayload_default_instance_;
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
template<> ::xwalk::iw::v1::XWalkI2cConfirmPayload* Arena::CreateMaybeMessage<::xwalk::iw::v1::XWalkI2cConfirmPayload>(Arena*);
template<> ::xwalk::iw::v1::XWalkI2cRejectPayload* Arena::CreateMaybeMessage<::xwalk::iw::v1::XWalkI2cRejectPayload>(Arena*);
template<> ::xwalk::iw::v1::XWalkI2cRequestPayload* Arena::CreateMaybeMessage<::xwalk::iw::v1::XWalkI2cRequestPayload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xwalk {
namespace iw {
namespace v1 {

// ===================================================================

class XWalkI2cRequestPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xwalk.iw.v1.XWalkI2cRequestPayload) */ {
 public:
  inline XWalkI2cRequestPayload() : XWalkI2cRequestPayload(nullptr) {}
  ~XWalkI2cRequestPayload() override;
  explicit PROTOBUF_CONSTEXPR XWalkI2cRequestPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XWalkI2cRequestPayload(const XWalkI2cRequestPayload& from);
  XWalkI2cRequestPayload(XWalkI2cRequestPayload&& from) noexcept
    : XWalkI2cRequestPayload() {
    *this = ::std::move(from);
  }

  inline XWalkI2cRequestPayload& operator=(const XWalkI2cRequestPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline XWalkI2cRequestPayload& operator=(XWalkI2cRequestPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XWalkI2cRequestPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const XWalkI2cRequestPayload* internal_default_instance() {
    return reinterpret_cast<const XWalkI2cRequestPayload*>(
               &_XWalkI2cRequestPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(XWalkI2cRequestPayload& a, XWalkI2cRequestPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(XWalkI2cRequestPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XWalkI2cRequestPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XWalkI2cRequestPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XWalkI2cRequestPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XWalkI2cRequestPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XWalkI2cRequestPayload& from) {
    XWalkI2cRequestPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XWalkI2cRequestPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xwalk.iw.v1.XWalkI2cRequestPayload";
  }
  protected:
  explicit XWalkI2cRequestPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 4,
    kAddressFieldNumber = 1,
    kRegisterAddressFieldNumber = 2,
    kLengthFieldNumber = 3,
    kOperationFieldNumber = 5,
  };
  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint32 address = 1;
  void clear_address();
  uint32_t address() const;
  void set_address(uint32_t value);
  private:
  uint32_t _internal_address() const;
  void _internal_set_address(uint32_t value);
  public:

  // uint32 register_address = 2;
  void clear_register_address();
  uint32_t register_address() const;
  void set_register_address(uint32_t value);
  private:
  uint32_t _internal_register_address() const;
  void _internal_set_register_address(uint32_t value);
  public:

  // uint32 length = 3;
  void clear_length();
  uint32_t length() const;
  void set_length(uint32_t value);
  private:
  uint32_t _internal_length() const;
  void _internal_set_length(uint32_t value);
  public:

  // .xwalk.iw.v1.XWalkI2cOperation operation = 5;
  void clear_operation();
  ::xwalk::iw::v1::XWalkI2cOperation operation() const;
  void set_operation(::xwalk::iw::v1::XWalkI2cOperation value);
  private:
  ::xwalk::iw::v1::XWalkI2cOperation _internal_operation() const;
  void _internal_set_operation(::xwalk::iw::v1::XWalkI2cOperation value);
  public:

  // @@protoc_insertion_point(class_scope:xwalk.iw.v1.XWalkI2cRequestPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    uint32_t address_;
    uint32_t register_address_;
    uint32_t length_;
    int operation_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xHal_5fRpi5CarXIwMessage_2eproto;
};
// -------------------------------------------------------------------

class XWalkI2cConfirmPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xwalk.iw.v1.XWalkI2cConfirmPayload) */ {
 public:
  inline XWalkI2cConfirmPayload() : XWalkI2cConfirmPayload(nullptr) {}
  ~XWalkI2cConfirmPayload() override;
  explicit PROTOBUF_CONSTEXPR XWalkI2cConfirmPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XWalkI2cConfirmPayload(const XWalkI2cConfirmPayload& from);
  XWalkI2cConfirmPayload(XWalkI2cConfirmPayload&& from) noexcept
    : XWalkI2cConfirmPayload() {
    *this = ::std::move(from);
  }

  inline XWalkI2cConfirmPayload& operator=(const XWalkI2cConfirmPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline XWalkI2cConfirmPayload& operator=(XWalkI2cConfirmPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XWalkI2cConfirmPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const XWalkI2cConfirmPayload* internal_default_instance() {
    return reinterpret_cast<const XWalkI2cConfirmPayload*>(
               &_XWalkI2cConfirmPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(XWalkI2cConfirmPayload& a, XWalkI2cConfirmPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(XWalkI2cConfirmPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XWalkI2cConfirmPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XWalkI2cConfirmPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XWalkI2cConfirmPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XWalkI2cConfirmPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XWalkI2cConfirmPayload& from) {
    XWalkI2cConfirmPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XWalkI2cConfirmPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xwalk.iw.v1.XWalkI2cConfirmPayload";
  }
  protected:
  explicit XWalkI2cConfirmPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kRespondingFieldNumber = 2,
  };
  // bytes data = 1;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // bool responding = 2;
  void clear_responding();
  bool responding() const;
  void set_responding(bool value);
  private:
  bool _internal_responding() const;
  void _internal_set_responding(bool value);
  public:

  // @@protoc_insertion_point(class_scope:xwalk.iw.v1.XWalkI2cConfirmPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    bool responding_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xHal_5fRpi5CarXIwMessage_2eproto;
};
// -------------------------------------------------------------------

class XWalkI2cRejectPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xwalk.iw.v1.XWalkI2cRejectPayload) */ {
 public:
  inline XWalkI2cRejectPayload() : XWalkI2cRejectPayload(nullptr) {}
  ~XWalkI2cRejectPayload() override;
  explicit PROTOBUF_CONSTEXPR XWalkI2cRejectPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XWalkI2cRejectPayload(const XWalkI2cRejectPayload& from);
  XWalkI2cRejectPayload(XWalkI2cRejectPayload&& from) noexcept
    : XWalkI2cRejectPayload() {
    *this = ::std::move(from);
  }

  inline XWalkI2cRejectPayload& operator=(const XWalkI2cRejectPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline XWalkI2cRejectPayload& operator=(XWalkI2cRejectPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XWalkI2cRejectPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const XWalkI2cRejectPayload* internal_default_instance() {
    return reinterpret_cast<const XWalkI2cRejectPayload*>(
               &_XWalkI2cRejectPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(XWalkI2cRejectPayload& a, XWalkI2cRejectPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(XWalkI2cRejectPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XWalkI2cRejectPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XWalkI2cRejectPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XWalkI2cRejectPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XWalkI2cRejectPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XWalkI2cRejectPayload& from) {
    XWalkI2cRejectPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XWalkI2cRejectPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xwalk.iw.v1.XWalkI2cRejectPayload";
  }
  protected:
  explicit XWalkI2cRejectPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetailFieldNumber = 2,
    kReasonFieldNumber = 1,
  };
  // string detail = 2;
  void clear_detail();
  const std::string& detail() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_detail(ArgT0&& arg0, ArgT... args);
  std::string* mutable_detail();
  PROTOBUF_NODISCARD std::string* release_detail();
  void set_allocated_detail(std::string* detail);
  private:
  const std::string& _internal_detail() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_detail(const std::string& value);
  std::string* _internal_mutable_detail();
  public:

  // uint32 reason = 1;
  void clear_reason();
  uint32_t reason() const;
  void set_reason(uint32_t value);
  private:
  uint32_t _internal_reason() const;
  void _internal_set_reason(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:xwalk.iw.v1.XWalkI2cRejectPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr detail_;
    uint32_t reason_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xHal_5fRpi5CarXIwMessage_2eproto;
};
// ===================================================================

static const int kXwalkSignalFieldNumber = 50001;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false >
  xwalkSignal;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XWalkI2cRequestPayload

// uint32 address = 1;
inline void XWalkI2cRequestPayload::clear_address() {
  _impl_.address_ = 0u;
}
inline uint32_t XWalkI2cRequestPayload::_internal_address() const {
  return _impl_.address_;
}
inline uint32_t XWalkI2cRequestPayload::address() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRequestPayload.address)
  return _internal_address();
}
inline void XWalkI2cRequestPayload::_internal_set_address(uint32_t value) {
  
  _impl_.address_ = value;
}
inline void XWalkI2cRequestPayload::set_address(uint32_t value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRequestPayload.address)
}

// uint32 register_address = 2;
inline void XWalkI2cRequestPayload::clear_register_address() {
  _impl_.register_address_ = 0u;
}
inline uint32_t XWalkI2cRequestPayload::_internal_register_address() const {
  return _impl_.register_address_;
}
inline uint32_t XWalkI2cRequestPayload::register_address() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRequestPayload.register_address)
  return _internal_register_address();
}
inline void XWalkI2cRequestPayload::_internal_set_register_address(uint32_t value) {
  
  _impl_.register_address_ = value;
}
inline void XWalkI2cRequestPayload::set_register_address(uint32_t value) {
  _internal_set_register_address(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRequestPayload.register_address)
}

// uint32 length = 3;
inline void XWalkI2cRequestPayload::clear_length() {
  _impl_.length_ = 0u;
}
inline uint32_t XWalkI2cRequestPayload::_internal_length() const {
  return _impl_.length_;
}
inline uint32_t XWalkI2cRequestPayload::length() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRequestPayload.length)
  return _internal_length();
}
inline void XWalkI2cRequestPayload::_internal_set_length(uint32_t value) {
  
  _impl_.length_ = value;
}
inline void XWalkI2cRequestPayload::set_length(uint32_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRequestPayload.length)
}

// bytes data = 4;
inline void XWalkI2cRequestPayload::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& XWalkI2cRequestPayload::data() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRequestPayload.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XWalkI2cRequestPayload::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRequestPayload.data)
}
inline std::string* XWalkI2cRequestPayload::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:xwalk.iw.v1.XWalkI2cRequestPayload.data)
  return _s;
}
inline const std::string& XWalkI2cRequestPayload::_internal_data() const {
  return _impl_.data_.Get();
}
inline void XWalkI2cRequestPayload::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* XWalkI2cRequestPayload::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* XWalkI2cRequestPayload::release_data() {
  // @@protoc_insertion_point(field_release:xwalk.iw.v1.XWalkI2cRequestPayload.data)
  return _impl_.data_.Release();
}
inline void XWalkI2cRequestPayload::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xwalk.iw.v1.XWalkI2cRequestPayload.data)
}

// .xwalk.iw.v1.XWalkI2cOperation operation = 5;
inline void XWalkI2cRequestPayload::clear_operation() {
  _impl_.operation_ = 0;
}
inline ::xwalk::iw::v1::XWalkI2cOperation XWalkI2cRequestPayload::_internal_operation() const {
  return static_cast< ::xwalk::iw::v1::XWalkI2cOperation >(_impl_.operation_);
}
inline ::xwalk::iw::v1::XWalkI2cOperation XWalkI2cRequestPayload::operation() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRequestPayload.operation)
  return _internal_operation();
}
inline void XWalkI2cRequestPayload::_internal_set_operation(::xwalk::iw::v1::XWalkI2cOperation value) {
  
  _impl_.operation_ = value;
}
inline void XWalkI2cRequestPayload::set_operation(::xwalk::iw::v1::XWalkI2cOperation value) {
  _internal_set_operation(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRequestPayload.operation)
}

// -------------------------------------------------------------------

// XWalkI2cConfirmPayload

// bytes data = 1;
inline void XWalkI2cConfirmPayload::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& XWalkI2cConfirmPayload::data() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cConfirmPayload.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XWalkI2cConfirmPayload::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cConfirmPayload.data)
}
inline std::string* XWalkI2cConfirmPayload::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:xwalk.iw.v1.XWalkI2cConfirmPayload.data)
  return _s;
}
inline const std::string& XWalkI2cConfirmPayload::_internal_data() const {
  return _impl_.data_.Get();
}
inline void XWalkI2cConfirmPayload::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* XWalkI2cConfirmPayload::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* XWalkI2cConfirmPayload::release_data() {
  // @@protoc_insertion_point(field_release:xwalk.iw.v1.XWalkI2cConfirmPayload.data)
  return _impl_.data_.Release();
}
inline void XWalkI2cConfirmPayload::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xwalk.iw.v1.XWalkI2cConfirmPayload.data)
}

// bool responding = 2;
inline void XWalkI2cConfirmPayload::clear_responding() {
  _impl_.responding_ = false;
}
inline bool XWalkI2cConfirmPayload::_internal_responding() const {
  return _impl_.responding_;
}
inline bool XWalkI2cConfirmPayload::responding() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cConfirmPayload.responding)
  return _internal_responding();
}
inline void XWalkI2cConfirmPayload::_internal_set_responding(bool value) {
  
  _impl_.responding_ = value;
}
inline void XWalkI2cConfirmPayload::set_responding(bool value) {
  _internal_set_responding(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cConfirmPayload.responding)
}

// -------------------------------------------------------------------

// XWalkI2cRejectPayload

// uint32 reason = 1;
inline void XWalkI2cRejectPayload::clear_reason() {
  _impl_.reason_ = 0u;
}
inline uint32_t XWalkI2cRejectPayload::_internal_reason() const {
  return _impl_.reason_;
}
inline uint32_t XWalkI2cRejectPayload::reason() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRejectPayload.reason)
  return _internal_reason();
}
inline void XWalkI2cRejectPayload::_internal_set_reason(uint32_t value) {
  
  _impl_.reason_ = value;
}
inline void XWalkI2cRejectPayload::set_reason(uint32_t value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRejectPayload.reason)
}

// string detail = 2;
inline void XWalkI2cRejectPayload::clear_detail() {
  _impl_.detail_.ClearToEmpty();
}
inline const std::string& XWalkI2cRejectPayload::detail() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XWalkI2cRejectPayload.detail)
  return _internal_detail();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XWalkI2cRejectPayload::set_detail(ArgT0&& arg0, ArgT... args) {
 
 _impl_.detail_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XWalkI2cRejectPayload.detail)
}
inline std::string* XWalkI2cRejectPayload::mutable_detail() {
  std::string* _s = _internal_mutable_detail();
  // @@protoc_insertion_point(field_mutable:xwalk.iw.v1.XWalkI2cRejectPayload.detail)
  return _s;
}
inline const std::string& XWalkI2cRejectPayload::_internal_detail() const {
  return _impl_.detail_.Get();
}
inline void XWalkI2cRejectPayload::_internal_set_detail(const std::string& value) {
  
  _impl_.detail_.Set(value, GetArenaForAllocation());
}
inline std::string* XWalkI2cRejectPayload::_internal_mutable_detail() {
  
  return _impl_.detail_.Mutable(GetArenaForAllocation());
}
inline std::string* XWalkI2cRejectPayload::release_detail() {
  // @@protoc_insertion_point(field_release:xwalk.iw.v1.XWalkI2cRejectPayload.detail)
  return _impl_.detail_.Release();
}
inline void XWalkI2cRejectPayload::set_allocated_detail(std::string* detail) {
  if (detail != nullptr) {
    
  } else {
    
  }
  _impl_.detail_.SetAllocated(detail, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.detail_.IsDefault()) {
    _impl_.detail_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xwalk.iw.v1.XWalkI2cRejectPayload.detail)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace iw
}  // namespace xwalk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwMessage_2eproto
