// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: xHal_Rpi5CarXIwGrpc.proto
// Original file comments:
// *****************************************************************************
// @file        xHal_Rpi5CarXIwGrpc.proto
// @brief       Defines the public gRPC service for xWalk I2C.
//
// @details
// Defines one generic request-confirmation RPC using the payload messages from
// `xHal_Rpi5CarXIwMessage.proto`.
//
// @project     xWalk Firmware
// @module      xWalkIW
//
// @author      Joxy John
// @date        2026-07-30
// @version     1.0.0
//
// @copyright
// Copyright (c) 2026 Joxy John.
// All rights reserved.
//
// @note
// Developed using MISRA C++ coding guidelines.
// ****************************************************************************
//
#ifndef GRPC_xHal_5fRpi5CarXIwGrpc_2eproto__INCLUDED
#define GRPC_xHal_5fRpi5CarXIwGrpc_2eproto__INCLUDED

#include "xHal_Rpi5CarXIwGrpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace xwalk {
namespace iw {
namespace v1 {

// *****************************************************************************
// Service declarations
// ****************************************************************************
//
// *
// @brief Provides one generic request-confirmation exchange for xWalk I2C.
//
// @details
// The request operation selects probe, direct read, register read, or register
// write. A successful call returns the shared confirmation payload. A rejected
// call returns a non-OK gRPC status with rejection details.
class XWalkI2cService final {
 public:
  static constexpr char const* service_full_name() {
    return "xwalk.iw.v1.XWalkI2cService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xwalk::iw::v1::XWalkI2cConfirmPayload>> AsyncExecute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xwalk::iw::v1::XWalkI2cConfirmPayload>>(AsyncExecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xwalk::iw::v1::XWalkI2cConfirmPayload>> PrepareAsyncExecute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xwalk::iw::v1::XWalkI2cConfirmPayload>>(PrepareAsyncExecuteRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* AsyncExecuteRaw(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>> AsyncExecute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>>(AsyncExecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>> PrepareAsyncExecute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>>(PrepareAsyncExecuteRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response, std::function<void(::grpc::Status)>) override;
      void Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* AsyncExecuteRaw(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Execute_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Execute(::grpc::ServerContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Execute() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecute(::grpc::ServerContext* context, ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::grpc::ServerAsyncResponseWriter< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Execute<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Execute() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response) { return this->Execute(context, request, response); }));}
    void SetMessageAllocatorFor_Execute(
        ::grpc::MessageAllocator< ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Execute(
      ::grpc::CallbackServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Execute<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Execute() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Execute() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Execute() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Execute(context, request, response); }));
    }
    ~WithRawCallbackMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Execute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Execute() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload>* streamer) {
                       return this->StreamedExecute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::xwalk::iw::v1::XWalkI2cRequestPayload* /*request*/, ::xwalk::iw::v1::XWalkI2cConfirmPayload* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::xwalk::iw::v1::XWalkI2cRequestPayload,::xwalk::iw::v1::XWalkI2cConfirmPayload>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Execute<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Execute<Service > StreamedService;
};

}  // namespace v1
}  // namespace iw
}  // namespace xwalk


#endif  // GRPC_xHal_5fRpi5CarXIwGrpc_2eproto__INCLUDED
