// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwEnum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwEnum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwEnum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xHal_5fRpi5CarXIwEnum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_xHal_5fRpi5CarXIwEnum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace xwalk {
namespace iw {
namespace v1 {

enum XWalkI2cOperation : int {
  XWALK_I2C_OPERATION_UNSPECIFIED = 0,
  XWALK_I2C_OPERATION_PROBE = 1,
  XWALK_I2C_OPERATION_READ = 2,
  XWALK_I2C_OPERATION_READ_REGISTER = 3,
  XWALK_I2C_OPERATION_WRITE_REGISTER = 4,
  XWalkI2cOperation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkI2cOperation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkI2cOperation_IsValid(int value);
constexpr XWalkI2cOperation XWalkI2cOperation_MIN = XWALK_I2C_OPERATION_UNSPECIFIED;
constexpr XWalkI2cOperation XWalkI2cOperation_MAX = XWALK_I2C_OPERATION_WRITE_REGISTER;
constexpr int XWalkI2cOperation_ARRAYSIZE = XWalkI2cOperation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkI2cOperation_descriptor();
template<typename T>
inline const std::string& XWalkI2cOperation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkI2cOperation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkI2cOperation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkI2cOperation_descriptor(), enum_t_value);
}
inline bool XWalkI2cOperation_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkI2cOperation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkI2cOperation>(
    XWalkI2cOperation_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace iw
}  // namespace xwalk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkI2cOperation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkI2cOperation>() {
  return ::xwalk::iw::v1::XWalkI2cOperation_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwEnum_2eproto
