// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: xHal_Rpi5CarXIwGrpc.proto

#include "xHal_Rpi5CarXIwGrpc.pb.h"
#include "xHal_Rpi5CarXIwGrpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace xwalk {
namespace iw {
namespace v1 {

static const char* XWalkI2cService_method_names[] = {
  "/xwalk.iw.v1.XWalkI2cService/Execute",
};

std::unique_ptr< XWalkI2cService::Stub> XWalkI2cService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< XWalkI2cService::Stub> stub(new XWalkI2cService::Stub(channel, options));
  return stub;
}

XWalkI2cService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Execute_(XWalkI2cService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status XWalkI2cService::Stub::Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response) {
  return ::grpc::internal::BlockingUnaryCall< ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Execute_, context, request, response);
}

void XWalkI2cService::Stub::async::Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, std::move(f));
}

void XWalkI2cService::Stub::async::Execute(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* XWalkI2cService::Stub::PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::xwalk::iw::v1::XWalkI2cConfirmPayload, ::xwalk::iw::v1::XWalkI2cRequestPayload, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Execute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::xwalk::iw::v1::XWalkI2cConfirmPayload>* XWalkI2cService::Stub::AsyncExecuteRaw(::grpc::ClientContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteRaw(context, request, cq);
  result->StartCall();
  return result;
}

XWalkI2cService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      XWalkI2cService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< XWalkI2cService::Service, ::xwalk::iw::v1::XWalkI2cRequestPayload, ::xwalk::iw::v1::XWalkI2cConfirmPayload, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](XWalkI2cService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::xwalk::iw::v1::XWalkI2cRequestPayload* req,
             ::xwalk::iw::v1::XWalkI2cConfirmPayload* resp) {
               return service->Execute(ctx, req, resp);
             }, this)));
}

XWalkI2cService::Service::~Service() {
}

::grpc::Status XWalkI2cService::Service::Execute(::grpc::ServerContext* context, const ::xwalk::iw::v1::XWalkI2cRequestPayload* request, ::xwalk::iw::v1::XWalkI2cConfirmPayload* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace xwalk
}  // namespace iw
}  // namespace v1

