// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwEnum.proto

#include "xHal_Rpi5CarXIwEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xwalk {
namespace iw {
namespace v1 {
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xHal_5fRpi5CarXIwEnum_2eproto = nullptr;
const uint32_t TableStruct_xHal_5fRpi5CarXIwEnum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xHal_5fRpi5CarXIwEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031xHal_Rpi5CarXIwEnum.proto\022\013xwalk.iw.v1"
  "*\304\001\n\021XWalkI2cOperation\022#\n\037XWALK_I2C_OPER"
  "ATION_UNSPECIFIED\020\000\022\035\n\031XWALK_I2C_OPERATI"
  "ON_PROBE\020\001\022\034\n\030XWALK_I2C_OPERATION_READ\020\002"
  "\022%\n!XWALK_I2C_OPERATION_READ_REGISTER\020\003\022"
  "&\n\"XWALK_I2C_OPERATION_WRITE_REGISTER\020\004b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto = {
    false, false, 247, descriptor_table_protodef_xHal_5fRpi5CarXIwEnum_2eproto,
    "xHal_Rpi5CarXIwEnum.proto",
    &descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_xHal_5fRpi5CarXIwEnum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto,
    file_level_service_descriptors_xHal_5fRpi5CarXIwEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto_getter() {
  return &descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xHal_5fRpi5CarXIwEnum_2eproto(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
namespace xwalk {
namespace iw {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkI2cOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwEnum_2eproto[0];
}
bool XWalkI2cOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
