// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwMessage.proto

#include "xHal_Rpi5CarXIwMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xwalk {
namespace iw {
namespace v1 {
PROTOBUF_CONSTEXPR XWalkI2cRequestPayload::XWalkI2cRequestPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.address_)*/0u
  , /*decltype(_impl_.register_address_)*/0u
  , /*decltype(_impl_.length_)*/0u
  , /*decltype(_impl_.operation_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XWalkI2cRequestPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XWalkI2cRequestPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XWalkI2cRequestPayloadDefaultTypeInternal() {}
  union {
    XWalkI2cRequestPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XWalkI2cRequestPayloadDefaultTypeInternal _XWalkI2cRequestPayload_default_instance_;
PROTOBUF_CONSTEXPR XWalkI2cConfirmPayload::XWalkI2cConfirmPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.responding_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XWalkI2cConfirmPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XWalkI2cConfirmPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XWalkI2cConfirmPayloadDefaultTypeInternal() {}
  union {
    XWalkI2cConfirmPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XWalkI2cConfirmPayloadDefaultTypeInternal _XWalkI2cConfirmPayload_default_instance_;
PROTOBUF_CONSTEXPR XWalkI2cRejectPayload::XWalkI2cRejectPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.detail_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.reason_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XWalkI2cRejectPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XWalkI2cRejectPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XWalkI2cRejectPayloadDefaultTypeInternal() {}
  union {
    XWalkI2cRejectPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XWalkI2cRejectPayloadDefaultTypeInternal _XWalkI2cRejectPayload_default_instance_;
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
static ::_pb::Metadata file_level_metadata_xHal_5fRpi5CarXIwMessage_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_xHal_5fRpi5CarXIwMessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xHal_5fRpi5CarXIwMessage_2eproto = nullptr;

const uint32_t TableStruct_xHal_5fRpi5CarXIwMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRequestPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRequestPayload, _impl_.address_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRequestPayload, _impl_.register_address_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRequestPayload, _impl_.length_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRequestPayload, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRequestPayload, _impl_.operation_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cConfirmPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cConfirmPayload, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cConfirmPayload, _impl_.responding_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRejectPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRejectPayload, _impl_.reason_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XWalkI2cRejectPayload, _impl_.detail_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::xwalk::iw::v1::XWalkI2cRequestPayload)},
  { 11, -1, -1, sizeof(::xwalk::iw::v1::XWalkI2cConfirmPayload)},
  { 19, -1, -1, sizeof(::xwalk::iw::v1::XWalkI2cRejectPayload)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::xwalk::iw::v1::_XWalkI2cRequestPayload_default_instance_._instance,
  &::xwalk::iw::v1::_XWalkI2cConfirmPayload_default_instance_._instance,
  &::xwalk::iw::v1::_XWalkI2cRejectPayload_default_instance_._instance,
};

const char descriptor_table_protodef_xHal_5fRpi5CarXIwMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034xHal_Rpi5CarXIwMessage.proto\022\013xwalk.iw"
  ".v1\032 google/protobuf/descriptor.proto\032\031x"
  "Hal_Rpi5CarXIwEnum.proto\"\233\001\n\026XWalkI2cReq"
  "uestPayload\022\017\n\007address\030\001 \001(\r\022\030\n\020register"
  "_address\030\002 \001(\r\022\016\n\006length\030\003 \001(\r\022\014\n\004data\030\004"
  " \001(\014\0221\n\toperation\030\005 \001(\0162\036.xwalk.iw.v1.XW"
  "alkI2cOperation:\005\210\265\030\201!\"A\n\026XWalkI2cConfir"
  "mPayload\022\014\n\004data\030\001 \001(\014\022\022\n\nresponding\030\002 \001"
  "(\010:\005\210\265\030\202!\">\n\025XWalkI2cRejectPayload\022\016\n\006re"
  "ason\030\001 \001(\r\022\016\n\006detail\030\002 \001(\t:\005\210\265\030\203!:6\n\013xwa"
  "lkSignal\022\037.google.protobuf.MessageOption"
  "s\030\321\206\003 \001(\rb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
  &::descriptor_table_xHal_5fRpi5CarXIwEnum_2eproto,
};
static ::_pbi::once_flag descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto = {
    false, false, 457, descriptor_table_protodef_xHal_5fRpi5CarXIwMessage_2eproto,
    "xHal_Rpi5CarXIwMessage.proto",
    &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_once, descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_deps, 2, 3,
    schemas, file_default_instances, TableStruct_xHal_5fRpi5CarXIwMessage_2eproto::offsets,
    file_level_metadata_xHal_5fRpi5CarXIwMessage_2eproto, file_level_enum_descriptors_xHal_5fRpi5CarXIwMessage_2eproto,
    file_level_service_descriptors_xHal_5fRpi5CarXIwMessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_getter() {
  return &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xHal_5fRpi5CarXIwMessage_2eproto(&descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto);
namespace xwalk {
namespace iw {
namespace v1 {

// ===================================================================

class XWalkI2cRequestPayload::_Internal {
 public:
};

XWalkI2cRequestPayload::XWalkI2cRequestPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xwalk.iw.v1.XWalkI2cRequestPayload)
}
XWalkI2cRequestPayload::XWalkI2cRequestPayload(const XWalkI2cRequestPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XWalkI2cRequestPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.register_address_){}
    , decltype(_impl_.length_){}
    , decltype(_impl_.operation_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.address_, &from._impl_.address_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.operation_) -
    reinterpret_cast<char*>(&_impl_.address_)) + sizeof(_impl_.operation_));
  // @@protoc_insertion_point(copy_constructor:xwalk.iw.v1.XWalkI2cRequestPayload)
}

inline void XWalkI2cRequestPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.address_){0u}
    , decltype(_impl_.register_address_){0u}
    , decltype(_impl_.length_){0u}
    , decltype(_impl_.operation_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XWalkI2cRequestPayload::~XWalkI2cRequestPayload() {
  // @@protoc_insertion_point(destructor:xwalk.iw.v1.XWalkI2cRequestPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XWalkI2cRequestPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void XWalkI2cRequestPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XWalkI2cRequestPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:xwalk.iw.v1.XWalkI2cRequestPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.address_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.operation_) -
      reinterpret_cast<char*>(&_impl_.address_)) + sizeof(_impl_.operation_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XWalkI2cRequestPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.address_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 register_address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.register_address_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 length = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .xwalk.iw.v1.XWalkI2cOperation operation = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_operation(static_cast<::xwalk::iw::v1::XWalkI2cOperation>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XWalkI2cRequestPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xwalk.iw.v1.XWalkI2cRequestPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 address = 1;
  if (this->_internal_address() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_address(), target);
  }

  // uint32 register_address = 2;
  if (this->_internal_register_address() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_register_address(), target);
  }

  // uint32 length = 3;
  if (this->_internal_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_length(), target);
  }

  // bytes data = 4;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_data(), target);
  }

  // .xwalk.iw.v1.XWalkI2cOperation operation = 5;
  if (this->_internal_operation() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_operation(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xwalk.iw.v1.XWalkI2cRequestPayload)
  return target;
}

size_t XWalkI2cRequestPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xwalk.iw.v1.XWalkI2cRequestPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 4;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // uint32 address = 1;
  if (this->_internal_address() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_address());
  }

  // uint32 register_address = 2;
  if (this->_internal_register_address() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_register_address());
  }

  // uint32 length = 3;
  if (this->_internal_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_length());
  }

  // .xwalk.iw.v1.XWalkI2cOperation operation = 5;
  if (this->_internal_operation() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_operation());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XWalkI2cRequestPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XWalkI2cRequestPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XWalkI2cRequestPayload::GetClassData() const { return &_class_data_; }


void XWalkI2cRequestPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XWalkI2cRequestPayload*>(&to_msg);
  auto& from = static_cast<const XWalkI2cRequestPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xwalk.iw.v1.XWalkI2cRequestPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_address() != 0) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_register_address() != 0) {
    _this->_internal_set_register_address(from._internal_register_address());
  }
  if (from._internal_length() != 0) {
    _this->_internal_set_length(from._internal_length());
  }
  if (from._internal_operation() != 0) {
    _this->_internal_set_operation(from._internal_operation());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XWalkI2cRequestPayload::CopyFrom(const XWalkI2cRequestPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xwalk.iw.v1.XWalkI2cRequestPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XWalkI2cRequestPayload::IsInitialized() const {
  return true;
}

void XWalkI2cRequestPayload::InternalSwap(XWalkI2cRequestPayload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XWalkI2cRequestPayload, _impl_.operation_)
      + sizeof(XWalkI2cRequestPayload::_impl_.operation_)
      - PROTOBUF_FIELD_OFFSET(XWalkI2cRequestPayload, _impl_.address_)>(
          reinterpret_cast<char*>(&_impl_.address_),
          reinterpret_cast<char*>(&other->_impl_.address_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XWalkI2cRequestPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_getter, &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_once,
      file_level_metadata_xHal_5fRpi5CarXIwMessage_2eproto[0]);
}

// ===================================================================

class XWalkI2cConfirmPayload::_Internal {
 public:
};

XWalkI2cConfirmPayload::XWalkI2cConfirmPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xwalk.iw.v1.XWalkI2cConfirmPayload)
}
XWalkI2cConfirmPayload::XWalkI2cConfirmPayload(const XWalkI2cConfirmPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XWalkI2cConfirmPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.responding_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.responding_ = from._impl_.responding_;
  // @@protoc_insertion_point(copy_constructor:xwalk.iw.v1.XWalkI2cConfirmPayload)
}

inline void XWalkI2cConfirmPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.responding_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XWalkI2cConfirmPayload::~XWalkI2cConfirmPayload() {
  // @@protoc_insertion_point(destructor:xwalk.iw.v1.XWalkI2cConfirmPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XWalkI2cConfirmPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void XWalkI2cConfirmPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XWalkI2cConfirmPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:xwalk.iw.v1.XWalkI2cConfirmPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _impl_.responding_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XWalkI2cConfirmPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool responding = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.responding_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XWalkI2cConfirmPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xwalk.iw.v1.XWalkI2cConfirmPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_data(), target);
  }

  // bool responding = 2;
  if (this->_internal_responding() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_responding(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xwalk.iw.v1.XWalkI2cConfirmPayload)
  return target;
}

size_t XWalkI2cConfirmPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xwalk.iw.v1.XWalkI2cConfirmPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // bool responding = 2;
  if (this->_internal_responding() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XWalkI2cConfirmPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XWalkI2cConfirmPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XWalkI2cConfirmPayload::GetClassData() const { return &_class_data_; }


void XWalkI2cConfirmPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XWalkI2cConfirmPayload*>(&to_msg);
  auto& from = static_cast<const XWalkI2cConfirmPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xwalk.iw.v1.XWalkI2cConfirmPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_responding() != 0) {
    _this->_internal_set_responding(from._internal_responding());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XWalkI2cConfirmPayload::CopyFrom(const XWalkI2cConfirmPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xwalk.iw.v1.XWalkI2cConfirmPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XWalkI2cConfirmPayload::IsInitialized() const {
  return true;
}

void XWalkI2cConfirmPayload::InternalSwap(XWalkI2cConfirmPayload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  swap(_impl_.responding_, other->_impl_.responding_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XWalkI2cConfirmPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_getter, &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_once,
      file_level_metadata_xHal_5fRpi5CarXIwMessage_2eproto[1]);
}

// ===================================================================

class XWalkI2cRejectPayload::_Internal {
 public:
};

XWalkI2cRejectPayload::XWalkI2cRejectPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xwalk.iw.v1.XWalkI2cRejectPayload)
}
XWalkI2cRejectPayload::XWalkI2cRejectPayload(const XWalkI2cRejectPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XWalkI2cRejectPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.detail_){}
    , decltype(_impl_.reason_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.detail_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.detail_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_detail().empty()) {
    _this->_impl_.detail_.Set(from._internal_detail(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.reason_ = from._impl_.reason_;
  // @@protoc_insertion_point(copy_constructor:xwalk.iw.v1.XWalkI2cRejectPayload)
}

inline void XWalkI2cRejectPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.detail_){}
    , decltype(_impl_.reason_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.detail_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.detail_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XWalkI2cRejectPayload::~XWalkI2cRejectPayload() {
  // @@protoc_insertion_point(destructor:xwalk.iw.v1.XWalkI2cRejectPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XWalkI2cRejectPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.detail_.Destroy();
}

void XWalkI2cRejectPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XWalkI2cRejectPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:xwalk.iw.v1.XWalkI2cRejectPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.detail_.ClearToEmpty();
  _impl_.reason_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XWalkI2cRejectPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 reason = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.reason_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string detail = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_detail();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "xwalk.iw.v1.XWalkI2cRejectPayload.detail"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XWalkI2cRejectPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xwalk.iw.v1.XWalkI2cRejectPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 reason = 1;
  if (this->_internal_reason() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_reason(), target);
  }

  // string detail = 2;
  if (!this->_internal_detail().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_detail().data(), static_cast<int>(this->_internal_detail().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "xwalk.iw.v1.XWalkI2cRejectPayload.detail");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_detail(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xwalk.iw.v1.XWalkI2cRejectPayload)
  return target;
}

size_t XWalkI2cRejectPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xwalk.iw.v1.XWalkI2cRejectPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string detail = 2;
  if (!this->_internal_detail().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_detail());
  }

  // uint32 reason = 1;
  if (this->_internal_reason() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_reason());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XWalkI2cRejectPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XWalkI2cRejectPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XWalkI2cRejectPayload::GetClassData() const { return &_class_data_; }


void XWalkI2cRejectPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XWalkI2cRejectPayload*>(&to_msg);
  auto& from = static_cast<const XWalkI2cRejectPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xwalk.iw.v1.XWalkI2cRejectPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_detail().empty()) {
    _this->_internal_set_detail(from._internal_detail());
  }
  if (from._internal_reason() != 0) {
    _this->_internal_set_reason(from._internal_reason());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XWalkI2cRejectPayload::CopyFrom(const XWalkI2cRejectPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xwalk.iw.v1.XWalkI2cRejectPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XWalkI2cRejectPayload::IsInitialized() const {
  return true;
}

void XWalkI2cRejectPayload::InternalSwap(XWalkI2cRejectPayload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.detail_, lhs_arena,
      &other->_impl_.detail_, rhs_arena
  );
  swap(_impl_.reason_, other->_impl_.reason_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XWalkI2cRejectPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_getter, &descriptor_table_xHal_5fRpi5CarXIwMessage_2eproto_once,
      file_level_metadata_xHal_5fRpi5CarXIwMessage_2eproto[2]);
}
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  xwalkSignal(kXwalkSignalFieldNumber, 0u, nullptr);

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::xwalk::iw::v1::XWalkI2cRequestPayload*
Arena::CreateMaybeMessage< ::xwalk::iw::v1::XWalkI2cRequestPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xwalk::iw::v1::XWalkI2cRequestPayload >(arena);
}
template<> PROTOBUF_NOINLINE ::xwalk::iw::v1::XWalkI2cConfirmPayload*
Arena::CreateMaybeMessage< ::xwalk::iw::v1::XWalkI2cConfirmPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xwalk::iw::v1::XWalkI2cConfirmPayload >(arena);
}
template<> PROTOBUF_NOINLINE ::xwalk::iw::v1::XWalkI2cRejectPayload*
Arena::CreateMaybeMessage< ::xwalk::iw::v1::XWalkI2cRejectPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xwalk::iw::v1::XWalkI2cRejectPayload >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
