#!/usr/bin/env python3
"""Verify Gerrit patch sets and mirror submitted changes to GitHub."""

from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile
import time
from typing import Any, TextIO

from xWalkGerritQuality import XWalkGerritQuality


class XWalkGerritCi:
    """Own Gerrit verification and submitted-change GitHub mirroring."""

    def __init__(self) -> None:
        """Load the fixed service configuration from the container environment."""

        self.host = os.environ.get("GERRIT_HOST", "127.0.0.1")
        self.port = os.environ.get("GERRIT_SSH_PORT", "29418")
        self.user = os.environ.get("GERRIT_USER", "xwalk-ci")
        self.project = os.environ.get("GERRIT_PROJECT", "xWalkPiCarAI")
        self.branch = os.environ.get("GERRIT_BRANCH", "master")
        self.private_key = Path(
            os.environ.get("GERRIT_SSH_KEY", "/run/secrets/gerrit_ssh_key")
        )
        self.github_host = os.environ.get("GITHUB_HOST", "github.com")
        self.github_repository = os.environ.get(
            "GITHUB_REPOSITORY", "jochuuu/xWalkPiCarAI"
        )
        self.github_web_url = os.environ.get(
            "GITHUB_WEB_URL", "https://github.com/jochuuu/xWalkPiCarAI"
        ).rstrip("/")
        self.github_primary_merger_email = os.environ.get(
            "GITHUB_PRIMARY_MERGER_EMAIL", "joxjoh24@student.hh.se"
        ).casefold()
        self.github_review_branch = os.environ.get(
            "GITHUB_REVIEW_BRANCH", "gerrit-submitted"
        )
        self.github_private_key = Path(
            os.environ.get(
                "GITHUB_SSH_KEY", "/run/secrets/github_mirror_ssh_key"
            )
        )
        self.state_directory = Path(
            os.environ.get("XWALK_CI_STATE_DIRECTORY", "/var/lib/xwalk-gerrit-ci")
        )
        self.log_directory = Path(
            os.environ.get("XWALK_CI_LOG_DIRECTORY", "/var/log/xwalk-gerrit-ci")
        )
        self.state_directory.mkdir(parents=True, exist_ok=True)
        self.log_directory.mkdir(parents=True, exist_ok=True)

    def ssh_arguments(self) -> list[str]:
        """Return noninteractive SSH arguments shared by Git and Gerrit commands."""

        return [
            "ssh",
            "-i",
            str(self.private_key),
            "-o",
            "BatchMode=yes",
            "-o",
            "IdentitiesOnly=yes",
            "-o",
            "ServerAliveInterval=30",
            "-o",
            "ServerAliveCountMax=3",
            "-o",
            "StrictHostKeyChecking=accept-new",
            "-o",
            f"UserKnownHostsFile={self.state_directory / 'known_hosts'}",
            "-p",
            self.port,
            f"{self.user}@{self.host}",
        ]

    def git_environment(self) -> dict[str, str]:
        """Return a Git environment that uses the dedicated Gerrit SSH identity."""

        environment = os.environ.copy()
        ssh_command = self.ssh_arguments()[:-1]
        environment["GIT_SSH_COMMAND"] = shlex.join(ssh_command)
        return environment

    def github_git_environment(self) -> dict[str, str]:
        """Return a Git environment using the repository-scoped deploy key."""

        environment = os.environ.copy()
        ssh_command = [
            "ssh",
            "-i",
            str(self.github_private_key),
            "-o",
            "BatchMode=yes",
            "-o",
            "IdentitiesOnly=yes",
            "-o",
            "StrictHostKeyChecking=accept-new",
            "-o",
            f"UserKnownHostsFile={self.state_directory / 'github_known_hosts'}",
        ]
        environment["GIT_SSH_COMMAND"] = shlex.join(ssh_command)
        return environment

    def report(self, change: int, patch_set: int, vote: int, message: str) -> bool:
        """Post one Verified vote and patch-set message through Gerrit SSH."""

        target = f"{change},{patch_set}"
        command = " ".join(
            [
                "gerrit review",
                f"--label Verified={vote:+d}",
                "--tag autogenerated:xwalk-ci",
                f"--message {shlex.quote(message)}",
                "--notify NONE",
                shlex.quote(target),
            ]
        )
        result = subprocess.run(
            [*self.ssh_arguments(), command], check=False, text=True
        )
        return result.returncode == 0

    def post_message(self, change: int, patch_set: int, message: str) -> bool:
        """Post one informational CI message without changing a label vote."""

        target = f"{change},{patch_set}"
        command = " ".join(
            [
                "gerrit review",
                "--tag autogenerated:xwalk-ci",
                f"--message {shlex.quote(message)}",
                "--notify NONE",
                shlex.quote(target),
            ]
        )
        result = subprocess.run(
            [*self.ssh_arguments(), command], check=False, text=True
        )
        return result.returncode == 0

    @staticmethod
    def run_command(
        command: list[str], working_directory: Path, log: TextIO,
        environment: dict[str, str] | None = None,
    ) -> bool:
        """Run one verification command while appending combined output to its log."""

        log.write(f"\n$ {shlex.join(command)}\n")
        log.flush()
        result = subprocess.run(
            command,
            cwd=working_directory,
            env=environment,
            stdout=log,
            stderr=subprocess.STDOUT,
            check=False,
            text=True,
        )
        return result.returncode == 0

    @staticmethod
    def command_output(
        command: list[str], working_directory: Path, log: TextIO,
        environment: dict[str, str] | None = None,
    ) -> str:
        """Run one inspection command and return stripped output on success."""

        log.write(f"\n$ {shlex.join(command)}\n")
        log.flush()
        result = subprocess.run(
            command,
            cwd=working_directory,
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
            text=True,
        )
        log.write(result.stdout)
        log.flush()
        return result.stdout.strip() if result.returncode == 0 else ""

    @staticmethod
    def select_github_branch(
        owner_email: str,
        primary_merger_email: str,
        primary_branch: str,
        review_branch: str,
        gerrit_parent: str,
        github_revision: str,
    ) -> str:
        """Select master only for one directly applicable Joxy-owned change."""

        owner_is_primary_merger = (
            bool(owner_email)
            and owner_email.casefold() == primary_merger_email.casefold()
        )
        directly_applicable = (
            bool(gerrit_parent)
            and gerrit_parent == github_revision
        )
        return primary_branch if owner_is_primary_merger and directly_applicable else review_branch

    def verify(self, event: dict[str, Any]) -> None:
        """Fetch, build, test, and report one matching Gerrit patch set."""

        change_data = event["change"]
        patch_data = event["patchSet"]
        change = int(change_data["number"])
        patch_set = int(patch_data["number"])
        revision = str(patch_data["revision"])
        ref = str(patch_data["ref"])
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        log_path = self.log_directory / f"change-{change}-{patch_set}-{timestamp}.log"
        print(f"Verifying change {change}, patch set {patch_set}: {revision}", flush=True)
        self.report(change, patch_set, 0, "xWalk host verification started")

        temporary_directory = Path(
            tempfile.mkdtemp(prefix=f"xwalk-gerrit-{change}-{patch_set}-")
        )
        with log_path.open("w", encoding="utf-8") as log:
            commands = [
                (["git", "init", "--quiet"], temporary_directory, None),
                (
                    [
                        "git",
                        "remote",
                        "add",
                        "origin",
                        f"ssh://{self.user}@{self.host}:{self.port}/{self.project}",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    ["git", "fetch", "--depth=1", "origin", ref],
                    temporary_directory,
                    self.git_environment(),
                ),
                (
                    ["git", "checkout", "--detach", "FETCH_HEAD"],
                    temporary_directory,
                    None,
                ),
            ]
            checkout_passed = all(
                self.run_command(command, directory, log, environment)
                for command, directory, environment in commands
            )
            quality_results: dict[str, bool] = {}
            if checkout_passed:
                quality = XWalkGerritQuality(temporary_directory, log)
                quality_results = quality.run_all()
            passed = checkout_passed and all(quality_results.values())
        shutil.rmtree(temporary_directory, ignore_errors=True)

        job_summary = [
            f"{name}: {'PASSED' if job_passed else 'FAILED'}"
            for name, job_passed in quality_results.items()
        ]
        if passed:
            message = "\n".join(
                [
                    "Complete xWalk host quality gate passed",
                    f"Jobs: {len(quality_results)}/{len(quality_results)}",
                    *job_summary,
                    f"Log: {log_path.name}",
                ]
            )
            vote = 1
        else:
            failed_jobs = [
                name for name, job_passed in quality_results.items() if not job_passed
            ]
            failure_summary = ", ".join(failed_jobs) if failed_jobs else "checkout"
            message = "\n".join(
                [
                    "Complete xWalk host quality gate failed",
                    f"Failed jobs: {failure_summary}",
                    *job_summary,
                    f"Log: {log_path.name}",
                ]
            )
            vote = -1
        reported = self.report(change, patch_set, vote, message)
        print(f"{message}; Gerrit report accepted={reported}", flush=True)

    def mirror(self, event: dict[str, Any]) -> None:
        """Publish a submitted change to GitHub master or its review branch."""

        change_data = event["change"]
        patch_data = event["patchSet"]
        change = int(change_data["number"])
        patch_set = int(patch_data["number"])
        revision = str(event["newRev"])
        owner_data = change_data.get("owner", {})
        owner_email = ""
        if isinstance(owner_data, dict):
            owner_email = str(owner_data.get("email", ""))
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        log_path = self.log_directory / f"mirror-{change}-{patch_set}-{timestamp}.log"
        print(f"Mirroring merged change {change}: {revision}", flush=True)

        temporary_directory = Path(
            tempfile.mkdtemp(prefix=f"xwalk-github-mirror-{change}-")
        )
        with log_path.open("w", encoding="utf-8") as log:
            commands = [
                (["git", "init", "--quiet"], temporary_directory, None),
                (
                    [
                        "git",
                        "remote",
                        "add",
                        "gerrit",
                        f"ssh://{self.user}@{self.host}:{self.port}/{self.project}",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    [
                        "git", "fetch", "gerrit",
                        f"{revision}:refs/remotes/gerrit/submitted",
                    ],
                    temporary_directory,
                    self.git_environment(),
                ),
                (
                    [
                        "git",
                        "remote",
                        "add",
                        "github",
                        f"git@{self.github_host}:{self.github_repository}.git",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    [
                        "git", "fetch", "github",
                        f"refs/heads/{self.branch}:refs/remotes/github/{self.branch}",
                    ],
                    temporary_directory,
                    self.github_git_environment(),
                ),
            ]
            setup_passed = all(
                self.run_command(command, directory, log, environment)
                for command, directory, environment in commands
            )
            target_branch = self.github_review_branch
            if setup_passed:
                gerrit_parent = self.command_output(
                    ["git", "rev-parse", "refs/remotes/gerrit/submitted^"],
                    temporary_directory,
                    log,
                )
                github_revision = self.command_output(
                    ["git", "rev-parse", f"refs/remotes/github/{self.branch}"],
                    temporary_directory,
                    log,
                )
                target_branch = self.select_github_branch(
                    owner_email,
                    self.github_primary_merger_email,
                    self.branch,
                    self.github_review_branch,
                    gerrit_parent,
                    github_revision,
                )
                mirrored = self.run_command(
                    [
                        "git", "push", "github",
                        f"refs/remotes/gerrit/submitted:refs/heads/{target_branch}",
                    ],
                    temporary_directory,
                    log,
                    self.github_git_environment(),
                )
            else:
                mirrored = False
        shutil.rmtree(temporary_directory, ignore_errors=True)

        commit_url = f"{self.github_web_url}/commit/{revision}"
        if mirrored:
            if target_branch == self.branch:
                result_text = "Joxy-owned Gerrit change mirrored to GitHub master"
            else:
                result_text = "Gerrit change published for Joxy GitHub review"
            message = "\n".join([
                result_text,
                f"Owner: {owner_email or 'unavailable'}",
                f"Branch: {target_branch}",
                f"Commit: {commit_url}",
                f"Log: {log_path.name}",
            ])
        else:
            message = "\n".join(
                [
                    "GitHub mirror failed",
                    f"Target: {commit_url}",
                    f"Log: {log_path.name}",
                ]
            )
        reported = self.post_message(change, patch_set, message)
        print(f"{message}; Gerrit report accepted={reported}", flush=True)

    def matching_verification_event(self, event: dict[str, Any]) -> bool:
        """Report whether an event requires configured host verification."""

        change = event.get("change", {})
        return (
            event.get("type") == "patchset-created"
            and change.get("project") == self.project
            and change.get("branch") == self.branch
            and isinstance(event.get("patchSet"), dict)
        )

    def matching_merge_event(self, event: dict[str, Any]) -> bool:
        """Report whether a submitted change must be mirrored to GitHub."""

        change = event.get("change", {})
        return (
            event.get("type") == "change-merged"
            and change.get("project") == self.project
            and change.get("branch") == self.branch
            and isinstance(event.get("patchSet"), dict)
            and isinstance(event.get("newRev"), str)
        )

    def consume_stream(self) -> None:
        """Consume one Gerrit event-stream connection until it closes."""

        command = [*self.ssh_arguments(), "gerrit stream-events"]
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            stripped = line.strip()
            if not stripped.startswith("{"):
                print(stripped, flush=True)
                continue
            event = json.loads(stripped)
            if self.matching_verification_event(event):
                self.verify(event)
            elif self.matching_merge_event(event):
                self.mirror(event)
        process.wait()

    def run(self) -> None:
        """Reconnect indefinitely so temporary Gerrit outages do not stop CI."""

        if not self.private_key.is_file():
            raise SystemExit(f"Missing Gerrit SSH key: {self.private_key}")
        if not self.github_private_key.is_file():
            raise SystemExit(f"Missing GitHub mirror SSH key: {self.github_private_key}")
        while True:
            self.consume_stream()
            print("Gerrit event stream closed; reconnecting in five seconds", flush=True)
            time.sleep(5)


if __name__ == "__main__":
    XWalkGerritCi().run()
