#!/usr/bin/env python3
"""Verify Gerrit patch sets and mirror submitted changes to GitHub."""

from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile
import time
from typing import Any, TextIO


class XWalkGerritCi:
    """Own Gerrit verification and submitted-change GitHub mirroring."""

    def __init__(self) -> None:
        """Load the fixed service configuration from the container environment."""

        self.host = os.environ.get("GERRIT_HOST", "127.0.0.1")
        self.port = os.environ.get("GERRIT_SSH_PORT", "29418")
        self.user = os.environ.get("GERRIT_USER", "xwalk-ci")
        self.project = os.environ.get("GERRIT_PROJECT", "xWalkPiCarAI")
        self.branch = os.environ.get("GERRIT_BRANCH", "master")
        self.private_key = Path(
            os.environ.get("GERRIT_SSH_KEY", "/run/secrets/gerrit_ssh_key")
        )
        self.github_host = os.environ.get("GITHUB_HOST", "github.com")
        self.github_repository = os.environ.get(
            "GITHUB_REPOSITORY", "jochuuu/xWalkPiCarAI"
        )
        self.github_web_url = os.environ.get(
            "GITHUB_WEB_URL", "https://github.com/jochuuu/xWalkPiCarAI"
        ).rstrip("/")
        self.github_private_key = Path(
            os.environ.get(
                "GITHUB_SSH_KEY", "/run/secrets/github_mirror_ssh_key"
            )
        )
        self.state_directory = Path(
            os.environ.get("XWALK_CI_STATE_DIRECTORY", "/var/lib/xwalk-gerrit-ci")
        )
        self.log_directory = Path(
            os.environ.get("XWALK_CI_LOG_DIRECTORY", "/var/log/xwalk-gerrit-ci")
        )
        self.state_directory.mkdir(parents=True, exist_ok=True)
        self.log_directory.mkdir(parents=True, exist_ok=True)

    def ssh_arguments(self) -> list[str]:
        """Return noninteractive SSH arguments shared by Git and Gerrit commands."""

        return [
            "ssh",
            "-i",
            str(self.private_key),
            "-o",
            "BatchMode=yes",
            "-o",
            "IdentitiesOnly=yes",
            "-o",
            "ServerAliveInterval=30",
            "-o",
            "ServerAliveCountMax=3",
            "-o",
            "StrictHostKeyChecking=accept-new",
            "-o",
            f"UserKnownHostsFile={self.state_directory / 'known_hosts'}",
            "-p",
            self.port,
            f"{self.user}@{self.host}",
        ]

    def git_environment(self) -> dict[str, str]:
        """Return a Git environment that uses the dedicated Gerrit SSH identity."""

        environment = os.environ.copy()
        ssh_command = self.ssh_arguments()[:-1]
        environment["GIT_SSH_COMMAND"] = shlex.join(ssh_command)
        return environment

    def github_git_environment(self) -> dict[str, str]:
        """Return a Git environment using the repository-scoped deploy key."""

        environment = os.environ.copy()
        ssh_command = [
            "ssh",
            "-i",
            str(self.github_private_key),
            "-o",
            "BatchMode=yes",
            "-o",
            "IdentitiesOnly=yes",
            "-o",
            "StrictHostKeyChecking=accept-new",
            "-o",
            f"UserKnownHostsFile={self.state_directory / 'github_known_hosts'}",
        ]
        environment["GIT_SSH_COMMAND"] = shlex.join(ssh_command)
        return environment

    def report(self, change: int, patch_set: int, vote: int, message: str) -> bool:
        """Post one Verified vote and patch-set message through Gerrit SSH."""

        target = f"{change},{patch_set}"
        command = " ".join(
            [
                "gerrit review",
                f"--label Verified={vote:+d}",
                "--tag autogenerated:xwalk-ci",
                f"--message {shlex.quote(message)}",
                "--notify NONE",
                shlex.quote(target),
            ]
        )
        result = subprocess.run(
            [*self.ssh_arguments(), command], check=False, text=True
        )
        return result.returncode == 0

    def post_message(self, change: int, patch_set: int, message: str) -> bool:
        """Post one informational CI message without changing a label vote."""

        target = f"{change},{patch_set}"
        command = " ".join(
            [
                "gerrit review",
                "--tag autogenerated:xwalk-ci",
                f"--message {shlex.quote(message)}",
                "--notify NONE",
                shlex.quote(target),
            ]
        )
        result = subprocess.run(
            [*self.ssh_arguments(), command], check=False, text=True
        )
        return result.returncode == 0

    @staticmethod
    def run_command(
        command: list[str], working_directory: Path, log: TextIO,
        environment: dict[str, str] | None = None,
    ) -> bool:
        """Run one verification command while appending combined output to its log."""

        log.write(f"\n$ {shlex.join(command)}\n")
        log.flush()
        result = subprocess.run(
            command,
            cwd=working_directory,
            env=environment,
            stdout=log,
            stderr=subprocess.STDOUT,
            check=False,
            text=True,
        )
        return result.returncode == 0

    def verify(self, event: dict[str, Any]) -> None:
        """Fetch, build, test, and report one matching Gerrit patch set."""

        change_data = event["change"]
        patch_data = event["patchSet"]
        change = int(change_data["number"])
        patch_set = int(patch_data["number"])
        revision = str(patch_data["revision"])
        ref = str(patch_data["ref"])
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        log_path = self.log_directory / f"change-{change}-{patch_set}-{timestamp}.log"
        print(f"Verifying change {change}, patch set {patch_set}: {revision}", flush=True)
        self.report(change, patch_set, 0, "xWalk host verification started")

        temporary_directory = Path(
            tempfile.mkdtemp(prefix=f"xwalk-gerrit-{change}-{patch_set}-")
        )
        with log_path.open("w", encoding="utf-8") as log:
            commands = [
                (["git", "init", "--quiet"], temporary_directory, None),
                (
                    [
                        "git",
                        "remote",
                        "add",
                        "origin",
                        f"ssh://{self.user}@{self.host}:{self.port}/{self.project}",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    ["git", "fetch", "--depth=1", "origin", ref],
                    temporary_directory,
                    self.git_environment(),
                ),
                (
                    ["git", "checkout", "--detach", "FETCH_HEAD"],
                    temporary_directory,
                    None,
                ),
                (
                    [
                        "cmake",
                        "--fresh",
                        "-S",
                        ".",
                        "-B",
                        "build-host/gerrit",
                        "-G",
                        "Ninja",
                        "-DCMAKE_BUILD_TYPE=Debug",
                        "-DXWALK_ENABLE_STRICT_WARNINGS=ON",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    ["cmake", "--build", "build-host/gerrit", "--parallel"],
                    temporary_directory,
                    None,
                ),
                (
                    [
                        "ctest",
                        "--test-dir",
                        "build-host/gerrit",
                        "--output-on-failure",
                        "--no-tests=error",
                    ],
                    temporary_directory,
                    None,
                ),
            ]
            passed = all(
                self.run_command(command, directory, log, environment)
                for command, directory, environment in commands
            )
        shutil.rmtree(temporary_directory, ignore_errors=True)

        if passed:
            message = f"xWalk host verification passed. Log: {log_path.name}"
            vote = 1
        else:
            message = f"xWalk host verification failed. Log: {log_path.name}"
            vote = -1
        reported = self.report(change, patch_set, vote, message)
        print(f"{message}; Gerrit report accepted={reported}", flush=True)

    def mirror(self, event: dict[str, Any]) -> None:
        """Fast-forward GitHub to the Gerrit branch after one submitted change."""

        change_data = event["change"]
        patch_data = event["patchSet"]
        change = int(change_data["number"])
        patch_set = int(patch_data["number"])
        revision = str(event["newRev"])
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        log_path = self.log_directory / f"mirror-{change}-{patch_set}-{timestamp}.log"
        print(f"Mirroring merged change {change}: {revision}", flush=True)

        temporary_directory = Path(
            tempfile.mkdtemp(prefix=f"xwalk-github-mirror-{change}-")
        )
        with log_path.open("w", encoding="utf-8") as log:
            commands = [
                (["git", "init", "--quiet"], temporary_directory, None),
                (
                    [
                        "git",
                        "remote",
                        "add",
                        "gerrit",
                        f"ssh://{self.user}@{self.host}:{self.port}/{self.project}",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    ["git", "fetch", "gerrit", f"refs/heads/{self.branch}"],
                    temporary_directory,
                    self.git_environment(),
                ),
                (
                    [
                        "git",
                        "remote",
                        "add",
                        "github",
                        f"git@{self.github_host}:{self.github_repository}.git",
                    ],
                    temporary_directory,
                    None,
                ),
                (
                    ["git", "push", "github", f"FETCH_HEAD:refs/heads/{self.branch}"],
                    temporary_directory,
                    self.github_git_environment(),
                ),
            ]
            mirrored = all(
                self.run_command(command, directory, log, environment)
                for command, directory, environment in commands
            )
        shutil.rmtree(temporary_directory, ignore_errors=True)

        commit_url = f"{self.github_web_url}/commit/{revision}"
        if mirrored:
            message = "\n".join(
                [
                    "Gerrit change mirrored to GitHub",
                    f"Branch: {self.branch}",
                    f"Commit: {commit_url}",
                    f"Log: {log_path.name}",
                ]
            )
        else:
            message = "\n".join(
                [
                    "GitHub mirror failed",
                    f"Target: {commit_url}",
                    f"Log: {log_path.name}",
                ]
            )
        reported = self.post_message(change, patch_set, message)
        print(f"{message}; Gerrit report accepted={reported}", flush=True)

    def matching_verification_event(self, event: dict[str, Any]) -> bool:
        """Report whether an event requires configured host verification."""

        change = event.get("change", {})
        return (
            event.get("type") == "patchset-created"
            and change.get("project") == self.project
            and change.get("branch") == self.branch
            and isinstance(event.get("patchSet"), dict)
        )

    def matching_merge_event(self, event: dict[str, Any]) -> bool:
        """Report whether a submitted change must be mirrored to GitHub."""

        change = event.get("change", {})
        return (
            event.get("type") == "change-merged"
            and change.get("project") == self.project
            and change.get("branch") == self.branch
            and isinstance(event.get("patchSet"), dict)
            and isinstance(event.get("newRev"), str)
        )

    def consume_stream(self) -> None:
        """Consume one Gerrit event-stream connection until it closes."""

        command = [*self.ssh_arguments(), "gerrit stream-events"]
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            stripped = line.strip()
            if not stripped.startswith("{"):
                print(stripped, flush=True)
                continue
            event = json.loads(stripped)
            if self.matching_verification_event(event):
                self.verify(event)
            elif self.matching_merge_event(event):
                self.mirror(event)
        process.wait()

    def run(self) -> None:
        """Reconnect indefinitely so temporary Gerrit outages do not stop CI."""

        if not self.private_key.is_file():
            raise SystemExit(f"Missing Gerrit SSH key: {self.private_key}")
        if not self.github_private_key.is_file():
            raise SystemExit(f"Missing GitHub mirror SSH key: {self.github_private_key}")
        while True:
            self.consume_stream()
            print("Gerrit event stream closed; reconnecting in five seconds", flush=True)
            time.sleep(5)


if __name__ == "__main__":
    XWalkGerritCi().run()
